---
  - name: set hostname
    hostname:
      name: "{{ host_name }}"
      

  - name: enable epel
    yum:
      name: "epel-release"
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: yum update
    yum:
      name: "*"
      update_cache: "yes"
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: install aptitude
    apt:
      name: "aptitude"
      state: latest
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: apt upgrade
    apt:
      name: "*"
      state: latest
      update_cache: "yes"
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

